version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - composer install --no-interaction --prefer-dist

  build:
    commands:
      - echo "Running all tests sequentially..."
      - vendor/bin/phpunit --testsuite Unit

  post_build:
    commands:
      - echo "Test completed at $(date)"
      # ここにSlack通知やデプロイ処理を書く想定
      # - aws sns publish --topic-arn $SNS_TOPIC --message "Build completed"

reports:
  phpunit-reports:
    files:
      - "reports/junit.xml"
    file-format: JUNITXML

cache:
  paths:
    - vendor/**/*
