version: 0.2

# 並列実行: build-list + testsuite 方式（静的分割）

batch:
  fast-fail: false
  build-list:
    - identifier: shard_1
      env:
        variables:
          SHARD_NUM: "1"
    - identifier: shard_2
      env:
        variables:
          SHARD_NUM: "2"
    - identifier: shard_3
      env:
        variables:
          SHARD_NUM: "3"

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - composer install --no-interaction --prefer-dist

  build:
    commands:
      - echo "Running shard-${SHARD_NUM}..."
      - vendor/bin/phpunit --testsuite "shard-${SHARD_NUM}"

  post_build:
    commands:
      - echo "Shard ${SHARD_NUM} completed"

cache:
  paths:
    - vendor/**/*
