version: 0.2

# ============================================
# 並列実行版: --filter 方式
# ============================================
# codebuild-tests-run を使い、テストクラス名で --filter する方式
# PHPUnitが複数ファイルを引数に取れない問題を回避

batch:
  fast-fail: false
  build-fan-out:
    parallelism: 3

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - composer install --no-interaction --prefer-dist
      # codebuild-tests-run CLI のインストール（プリインストール済みの場合は不要）

  pre_build:
    commands:
      # テストファイル一覧を取得
      - |
        find tests -name '*Test.php' | sort > all_tests.txt
        echo "All test files:"
        cat all_tests.txt

  build:
    commands:
      - |
        # codebuild-tests-run でこのシャードが担当するファイルを取得
        # --parallelism と CODEBUILD_BATCH_BUILD_IDENTIFIER から自動計算
        MY_TESTS=$(codebuild-tests-run \
          --test-file-pattern 'tests/**/*Test.php' \
          --parallelism 3)
        
        echo "This shard will run:"
        echo "$MY_TESTS"
        
        if [ -z "$MY_TESTS" ]; then
          echo "No tests assigned to this shard"
          exit 0
        fi
        
        # テストファイルからクラス名を抽出して --filter 用の正規表現を作成
        FILTER_PATTERN=""
        for TEST_FILE in $MY_TESTS; do
          CLASS_NAME=$(basename "$TEST_FILE" .php)
          if [ -z "$FILTER_PATTERN" ]; then
            FILTER_PATTERN="$CLASS_NAME"
          else
            FILTER_PATTERN="${FILTER_PATTERN}|${CLASS_NAME}"
          fi
        done
        
        echo "Filter pattern: $FILTER_PATTERN"
        vendor/bin/phpunit --filter "($FILTER_PATTERN)" --log-junit reports/junit.xml

  post_build:
    commands:
      - |
        SHARD_INDEX=$(echo $CODEBUILD_BATCH_BUILD_IDENTIFIER | grep -oE '[0-9]+$')
        echo "Shard ${SHARD_INDEX} completed"

reports:
  phpunit-reports:
    files:
      - "reports/junit.xml"
    file-format: JUNITXML

cache:
  paths:
    - vendor/**/*
