version: 0.2

# =============================================================================
# PHPUnit 並列実行: build-list + testsuite 方式
# =============================================================================
#
# なぜ build-fan-out + codebuild-tests-run を使わないのか？
# ---------------------------------------------------------
# codebuild-tests-run はテストファイルのリストを返すが、
# PHPUnit は複数ファイルを引数に取れない。
#   ❌ vendor/bin/phpunit tests/A.php tests/B.php  → 最初のファイルのみ実行
#
# Jest や pytest なら素直に使えるが、PHPUnit では --filter への変換が必要で
# ハック的になるため、testsuite で事前に分割する方式を採用。
#
# =============================================================================

batch:
  fast-fail: false
  build-list:
    - identifier: shard_1
      env:
        variables:
          SHARD_NUM: "1"
    - identifier: shard_2
      env:
        variables:
          SHARD_NUM: "2"
    - identifier: shard_3
      env:
        variables:
          SHARD_NUM: "3"

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - composer install --no-interaction --prefer-dist

  build:
    commands:
      - echo "Running shard-${SHARD_NUM}..."
      - mkdir -p reports
      - vendor/bin/phpunit --testsuite "shard-${SHARD_NUM}" --log-junit "reports/junit-shard-${SHARD_NUM}.xml"

  post_build:
    commands:
      # post_build は全シャードで実行される
      # 通知やデプロイは特定シャードでのみ実行するよう条件分岐が必要
      - |
        if [ "${SHARD_NUM}" = "1" ]; then
          echo "Shard 1: Notification would be triggered here"
        else
          echo "Shard ${SHARD_NUM}: Skipping notification"
        fi

reports:
  phpunit-reports:
    files:
      - "reports/junit-*.xml"
    file-format: JUNITXML

cache:
  paths:
    - vendor/**/*
